### PR TITLE
Add .png illustrations to illustrations directory

### PR DESCRIPTION
**Pull request by njsfield**
Related #9

### CODE REVIEW

**Comment by bradreeder** [comment]
Looking good @njsfield 👍 bare in mind when you make commits to also add a message with the issue number it relates to:

`git commit -m 'commit description' -m 'related #issueNo'`

That way if you go into the issue a history of all the commits made against that issue will be there.

**Comment by bradreeder** [comment]
@njsfield Looking good. @des-des should correct me on this if I'm mistaken, but I'd aim to link all your commits to the issue they're related to in the commit message:

`git commit -m 'commit description' -m 'related #issueNumber'`

That way when you go into your issue every commit you've made against it will be linked to it in the chat history.

**Comment by njsfield** [comment]
Apologies- will do! :)

**Comment by bradreeder** [comment]
❤️

**Comment by bradreeder** [comment]
These are all looking ❤️ . That's a tonne of work for one day ^_^;

Thanks for referencing the issues but remember to give your commits descriptions as well like you were doing before. Something like:

`git commit -m 'add png of second scene' -m 'related #9'`

The text following the first '-m' `add png of second scene` will appear as the commit title and the text following the second '-m' `related #9` will appear as the commit message in that example. Only saying in case my prior message came across as asking you to not describe the commit in favour of only referencing the issue.

**Comment by njsfield** [comment]
Ah no problem! I must of been using the command wrong (without the second '-m') as I did add the 'add' messages but hadn't checked here, will do :)

**Review by jbesraa — APPROVED** [review]

**Comment by jbesraa** [comment]
looks amazing!

**Review by denesnori — APPROVED** [review]

**Review by denesnori — APPROVED** [review]

**Review by des-des — APPROVED** [review]
This is bad: 
image


Otherwise awesome!

**Comment by des-des** [comment]
@njsfield assuming you meant to assign me! If you want me to review + merge, pls assign!

**Comment by njsfield** [comment]
Apologies! Will do going forward

**Pull request merged**
