### PR TITLE
Feel blue changes

### PR DESCRIPTION
**Pull request by denesnori**
I intentionally left comments in the code..because I'm still uncertain whether we should keep the titles on the cards our remove them.

### CODE REVIEW

**Comment by des-des** [comment]
@denesnori fyi best thing is too leave a comment for the comment if you do not want qa to pick up

**Comment by des-des** [comment]
@denesnori I have already reviewed lots of these commits? Do you want me to review these again?

**Comment by des-des** [comment]
https://github.com/CYPIAPT-LNDSE/sdm-app/pull/29

**Comment by des-des** [comment]
@denesnori this pull is the same as the other one.. Shall I re-open that one: https://github.com/CYPIAPT-LNDSE/sdm-app/pull/29

**Comment by des-des** [comment]
ugh it looks like this is the same as other one

**Comment by denesnori** [comment]
This is different, I made my CSS last night, and then this morning we agreed on changing the design.
This branch is the one we plan to work on from now on.

**Comment by des-des** [comment]
@denesnori can you merge this with master?

**Pull request merged**
