### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by jbesraa**
problems: 
#16 need to change the color of the home icon, main title (SDMAPP) and the menu icon.
#17  start button is not responsive.

### CODE REVIEW

**Comment by jbesraa** [comment]
im working on the colors #16

**Comment by bradreeder** [comment]
@esraajb Looking at this as an outsider, I'm unsure what problem 1 refers to. If you go under the list of your [issues](https://github.com/CYPIAPT-LNDSE/sdm-app/issues) you should see under the issue name a '#' followed by a number. Every time you make a PR link to the issue you're working on in the description using the '#issueNumber' format and it will automatically link your pull request to that issue.

**Comment by jbesraa** [comment]
cool. changed.

thanks (:

**Comment by bradreeder** [comment]
No worries, thanks @esraajb . Also bare in mind the comment I made on another pull here: https://github.com/CYPIAPT-LNDSE/sdm-app/pull/12#issuecomment-276417635

It might seem a little pedantic, but it means over time that the issues will contain a complete history of all the work you've done on it which helps everyone in a project track progress. 😸

**Comment by njsfield** [comment]
@esraajb Let us know when you'd like us to review (change label to Awaiting Review)

**Review by njsfield — CHANGES_REQUESTED** [review]
Refactoring before review

**Comment by jbesraa** [comment]
last commit:
* changed classes name
* added Depression page
* added questions to the sidebar

**Review by njsfield — APPROVED** [review]

**Review by denesnori — APPROVED** [review]

**Comment by des-des** [comment]
@esraajb I am assigned to review but there are new commits being pushed up. reassign me when work is done on branch.

Also, add issue numbers to commit messages (in future)

**Comment by jbesraa** [comment]
sure. sorry.

**Comment by des-des** [comment]
No problem!

**Comment by jbesraa** [comment]
fixed merge conflicts

**Pull request merged**
